### ISSUE TITLE
give the feasibility to have constraints added as simple plug-in configurations and share among the community

### ISSUE THREAD

**Issue by devopstoday11** [devopstoday11/tarian#1]
The processes/files which needs to be marked as threats and take action against them, you already developed constraints. Give the flexibility to add constraints as add-ons (plug-ins) using a yaml file or json (preferably yaml). This will help to manage constraints easily. When using UI, these constraints should be built as yaml files in the background and saved as constraints configurations. 
I am telling as yaml or json, you can come up with whichever easy process idea you get. 
Basically, we want to make it easy to add/export/delete those constraints as a independent items. It will also help to easily share in the open-source community. For example, if a security expert figures out some process & it's files & it's logs are definitely a threat item(s), they can mark those are threats & add actions. The data related to that threat, what action to take, metadata & log data of that threat should be save as a configuration like a separate thing and can share that file (or few files) to opensource community of Tarian so that other Tarian Users can simply import that constraint configuration and add that threat related constraint config into their environment & be benefited from it without having to figure out same kind of threat again themselves. 

Please let me know if it makes sense or want to discuss.

**Comment by andylibrian** [comment]
If the exported configuration would be shared by committing it to a git repo, and if there would be a need to manually edit the exported config, then a format that's human-friendly would be suitable. For that, I agree to use yaml.

A functionality to import yaml files in a directory would be needed. Something like `-R` in `kubectl apply`.

**Comment by andylibrian** [comment]
Closing as this has been implemented
